### ISSUE TITLE
Column width in Bot response

### ISSUE THREAD

**Issue by jczhang07** [jakobdylanc/llmcord#71]
I have a wide screen but the Bot response only takes a narrow part.  It is a waste of space. 
How to increase that?

Thanks!

**Comment by jakobdylanc** [comment]
I also find this annoying! But unfortunately the width of embeds is not controllable in Discord. At least I'm 99% sure.

You could set `use_plain_responses: true` which uses plaintext responses instead of embeds. But this also:
- Disables streamed responses and warning messages
- Decreases the character limit from 4000 to 2000, so the bot's messages may get split up more often

The character limit decrease is another Discord limitation.
