### ISSUE TITLE
Text Limit and Max Token Setting

### ISSUE THREAD

**Issue by wastu01** [jakobdylanc/llmcord#76]
I'm curious about the configuration for `max_text` and `extra_api_parameters`. Since the maximum character limit for a single Discord message is 2,000 characters for standard users, setting `max_text` to 100,000 seems to exceed this limit or it will automatic message splitting ?

**Comment by jakobdylanc** [comment]
The "max_text" config does not control the length of the bot's responses. Rather, it controls how much text is allowed in a single user message.

Since llmcord supports text file attachments, the total amount of text in a user message can greatly exceed 2000. So "max_text" allows you to set a limit.

**Comment by wastu01** [comment]
Got it, thanks for clarifying! Here's my use case: I'm using this project to help with English learning.
Thanks for providing such an excellent project to seamlessly integrate chatbots into Discord.

![toeic_practice](https://github.com/user-attachments/assets/5723fd66-cb48-4584-8f19-a227f597d435)

**Comment by jakobdylanc** [comment]
Awesome! :)

**Comment by jakobdylanc** [comment]
I should clarify that "max_text" applies to *all* messages in the current conversation, not just user messages. So be careful setting it to such a low value like 120.

This would cause the bot's responses to get cut short if it exceeds 120 characters. You can tell this is happening whenever you see the ⚠️ warning appear.
